### ISSUE TITLE
Questions about the experiments

### ISSUE THREAD

**Issue by YouthBL** [MMorafah/FLIS#8]
Hello, sorry to bother you again. I want to ask for some implementation of the "COMMUNICATION EFFICIENCY" and "GENERALIZATION TO UNSEEN CLIENTS"  sections in "EXPERIMENTS". I am a bit confused about the calculation of the communication cost and how the newcomers join the federated learning at the end of the federated. I have no idea how to perform these experiments.

**Comment by MMorafah** [comment]
Hello,

The communication cost is being calculated by the number of parameters exchanged in the entire FL. For examples [#of models exchange per round upload and download]*[# of model parameters]*[# of rounds]. For newcomers, I think there were 20% of clients reserved as newcomers and did not participate at the initial FL. More details on this can be found in the paper.

**Comment by YouthBL** [comment]
Thanks a lot for your reply.
